apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdA==      # base64 of 'root'
  mysql-database: cmVzdG8=           # base64 of 'resto'
  mysql-user: cm9vdA==               # base64 of 'root'
  mysql-password: cm9vdA==           # base64 of 'root'